print("     === 01 ===")
from tasks.distance_00 import distance
print("     === 02 ===")
from tasks.circle_01 import circle
print("     === 03 ===")
from tasks.operations_02 import operations
print("     === 04 ===")
from tasks.favorite_movies_03 import favorite_movies
print("     === 05 ===")
from tasks.my_family_04 import my_family
print("     === 06 ===")
from tasks.zoo_05 import zoo
print("     === 07 ===")
from tasks.songs_list_06 import songs_list
print("     === 08 ===")
from tasks.secret_07 import secret
print("     === 09 ===")
from tasks.garden_08 import garden
print("     === 10 ===")
from tasks.shopping_09 import shopping
print("     === 11 ===")
from tasks.store_10 import store